apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-r-us-deployment
  namespace: notes-r-us
  labels:
    app: notes-r-us-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-r-us-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      # maxUnavailable: 1

  template:
    metadata:
      labels:
        app: notes-r-us-app

    spec:
      containers:
      - name: notes-r-us
        image: ghcr.io/l2dit/notesrus:32b91666e2348fe033b3656122dddf2928331591
        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"

        - name: ORIGNS
          value: "0.0.0.0"

        - name: DOMAIN
          value: "notesrus.nzdev.org"

        - name: HTTPS
          value: "true"

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-notes-r-us-app
              key: uri

