//! # Notes R Us
//! <div class="warning">
//!     This Crate Is Not For Use As Library
//! </div>
//!
//! Documentation for the note storing app from your dreams. One part missing from this
//! documentation is the database migrations crate [`notes_r_us_migrations`].
//!
//! ## Modules:
//! - [`backend`][^backend]
//! - [`cli`][^cli]
//! - [`entity`][^entity]
//!
//! ### Backend[^backend]
//! This module is where all the API routes are defined and logic is placed for them here
//! [`backend::Api`].
//!
//! ### CLI[^cli]
//! The CLI module implements the requried cli using clap here [`cli::Args`].
//!
//! ### Entity[^entity]
//! Entitys are a auto generated section of code generated by [sea-orm-cli](https://www.sea-ql.org/SeaORM/docs/generate-entity/sea-orm-cli/).

pub mod backend;
pub mod cli;
pub mod entity;
